version: '3'

services:  
  
# frontend Service with Vue.js framework
  frontend:
    # image: node:${NODE_VERSION}
    build:
      context: "."
      args:
       NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
      # - "5000:3000" #For json-server (development)
    networks:
      - network
    environment:
      NODE_ENV: development
      # VUE_APP_API_URL: ${API_URL}
    # command: sh -c "tail -f /dev/null"
    command: sh -c "npm install && npm run dev"

# Networks
networks:
  network: